# Generated by Django 5.2.8 on 2025-12-02 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Edited', 'Edited'), ('Deleted', 'Deleted')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='notes.noteversion')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_activities', to='authentication.profile')),
            ],
        ),
    ]
