# Generated by Django 5.2.8 on 2025-12-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_noteactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
