# Generated by Django 5.2.8 on 2025-12-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='tags',
        ),
    ]
